### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by Iriamu19** [charlesmulder/alsa-audient-id14#2]
I'm sorry I'm a novice.Can you tell me how to install, with more details please ?

**Comment by charlesmulder** [comment]
Hi @Iriamu19 

Thanks for reaching out. I haven't finished work on the module yet. You are the second person to enquire about it though. I am beginning to think I should finish it. 

I don't really have time at the moment, but let me start by improving the README. 

I'll schedule some time today.

**Comment by Iriamu19** [comment]
Hi, I come back :) Any news ?

**Comment by slavikator** [comment]
I was going to buy this interface but should reject this idea because of the lack of Linux support.  I have to choose something more generic, like SSL2

**Comment by WSINTRA** [comment]
I use it with Linux and it works perfectly out the box.

**Comment by slavikator** [comment]
> I use it with Linux and it works perfectly out the box.
> […](#)
> Sent from my iPhone
> On Sep 17, 2021, at 08:03, slavikator ***@***.***> wrote: ﻿ I was going to buy this interface but should reject this idea because of the lack of Linux support. I have to choose something more generic, like SSL2 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Great! So, how the direct monitoring can be adjusted if there is no software for Linux and no physical button for mix the signals between the inputs and DAW?

**Comment by WSINTRA** [comment]
https://linuxmusicians.com/viewtopic.php?t=16166
This topic has a lot of info. Me personally I didn’t use the internal monitoring so not sure the results. Sorry for saying perfectly without understanding all use cases.

**Comment by slavikator** [comment]
> https://linuxmusicians.com/viewtopic.php?t=16166 This topic has a lot of info. Me personally I didn’t use the internal monitoring so not sure the results. Sorry for saying perfectly without understanding all use cases.
> […](#)
> Sent from my iPhone
> On Sep 17, 2021, at 10:17, slavikator ***@***.***> wrote: ﻿ I use it with Linux and it works perfectly out the box. … Sent from my iPhone On Sep 17, 2021, at 08:03, slavikator @.***> wrote: ﻿ I was going to buy this interface but should reject this idea because of the lack of Linux support. I have to choose something more generic, like SSL2 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. Great! So, how the direct monitoring can be adjusted if there is no software for Linux and no physical button for mix the signals between the inputs and DAW? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Thanks for the link. Unfortunately, that topic is about Audient ID4 which does have a physical button for mix direct monitoring. ID14 - different story. There are a lot of options controlled by software.
