### ISSUE TITLE
ID4 audio actual?

### ISSUE THREAD

**Issue by bazil-studio** [charlesmulder/alsa-audient-id14#3]
**This is setup be cool for my ID4 ?**

**Comment by charlesmulder** [comment]
Hi. 

Unfortunately not. I found that I lacked the necessary knowledge to implement the driver. As such I am busy doing a BEng in Electronics. Will return to it when I have a better understanding of electronics and writing drivers in general. 

I became a bit skeptical about writing a driver for this device as I was not able to find any documentation on the microcontroller. Maybe I'll have better luck after my studies. 

I did contact Audient for documentation, but they only responded with "it's mostly USB Audio 2 compliant, good luck". 

I read that I should install the Window driver and sniff the USB traffic. I used Wireshark, but kinda got lost in the amount of data being transmitted. 

Maybe I'll give it another shot when I finish my studies in 2027. 

If anyone is keen to help me with it. Please let me know.
